const CSS_STYLE_PROPERTY_SOURCE = `
accentColor alignContent alignItems alignSelf alignmentBaseline all anchorName anchorScope
animation animationComposition animationDelay animationDirection animationDuration animationFillMode
animationIterationCount animationName animationPlayState animationRange animationRangeEnd
animationRangeStart animationTimeline animationTimingFunction appearance aspectRatio backdropFilter
backfaceVisibility background backgroundAttachment backgroundBlendMode backgroundClip backgroundColor
backgroundImage backgroundOrigin backgroundPosition backgroundPositionX backgroundPositionY
backgroundRepeat backgroundSize baselineShift baselineSource blockSize border borderBlock
borderBlockColor borderBlockEnd borderBlockEndColor borderBlockEndStyle borderBlockEndWidth
borderBlockStart borderBlockStartColor borderBlockStartStyle borderBlockStartWidth borderBlockStyle
borderBlockWidth borderBottom borderBottomColor borderBottomLeftRadius borderBottomRightRadius
borderBottomStyle borderBottomWidth borderCollapse borderColor borderEndEndRadius borderEndStartRadius
borderImage borderImageOutset borderImageRepeat borderImageSlice borderImageSource borderImageWidth
borderInline borderInlineColor borderInlineEnd borderInlineEndColor borderInlineEndStyle
borderInlineEndWidth borderInlineStart borderInlineStartColor borderInlineStartStyle
borderInlineStartWidth borderInlineStyle borderInlineWidth borderLeft borderLeftColor borderLeftStyle
borderLeftWidth borderRadius borderRight borderRightColor borderRightStyle borderRightWidth
borderSpacing borderStartEndRadius borderStartStartRadius borderStyle borderTop borderTopColor
borderTopLeftRadius borderTopRightRadius borderTopStyle borderTopWidth borderWidth bottom
boxDecorationBreak boxShadow boxSizing breakAfter breakBefore breakInside captionSide caretColor clear
clip clipPath clipRule color colorInterpolation colorInterpolationFilters colorScheme columnCount
columnFill columnGap columnRule columnRuleColor columnRuleStyle columnRuleWidth columnSpan columnWidth
columns contain containIntrinsicBlockSize containIntrinsicHeight containIntrinsicInlineSize
containIntrinsicSize containIntrinsicWidth container containerName containerType content
contentVisibility counterIncrement counterReset counterSet cssFloat cursor cx cy d direction display
dominantBaseline dynamicRangeLimit emptyCells fieldSizing fill fillOpacity fillRule filter flex
flexBasis flexDirection flexFlow flexGrow flexShrink flexWrap float floodColor floodOpacity font
fontFamily fontFeatureSettings fontKerning fontLanguageOverride fontOpticalSizing fontPalette fontSize
fontSizeAdjust fontStretch fontStyle fontSynthesis fontSynthesisSmallCaps fontSynthesisStyle
fontSynthesisWeight fontVariant fontVariantAlternates fontVariantCaps fontVariantEastAsian
fontVariantEmoji fontVariantLigatures fontVariantNumeric fontVariantPosition fontVariationSettings
fontWeight forcedColorAdjust gap grid gridArea gridAutoColumns gridAutoFlow gridAutoRows gridColumn
gridColumnEnd gridColumnGap gridColumnStart gridGap gridRow gridRowEnd gridRowGap gridRowStart
gridTemplate gridTemplateAreas gridTemplateColumns gridTemplateRows height hyphenateCharacter
hyphenateLimitChars hyphens imageOrientation imageRendering inlineSize inset insetBlock insetBlockEnd
insetBlockStart insetInline insetInlineEnd insetInlineStart isolation justifyContent justifyItems
justifySelf left letterSpacing lightingColor lineBreak lineHeight listStyle listStyleImage
listStylePosition listStyleType margin marginBlock marginBlockEnd marginBlockStart marginBottom
marginInline marginInlineEnd marginInlineStart marginLeft marginRight marginTop marker markerEnd markerMid
markerStart mask maskClip maskComposite maskImage maskMode maskOrigin maskPosition maskRepeat maskSize
maskType mathDepth mathShift mathStyle maxBlockSize maxHeight maxInlineSize maxWidth minBlockSize
minHeight minInlineSize minWidth mixBlendMode objectFit objectPosition offset offsetAnchor
offsetDistance offsetPath offsetPosition offsetRotate opacity order orphans outline outlineColor
outlineOffset outlineStyle outlineWidth overflow overflowAnchor overflowBlock overflowClipMargin
overflowInline overflowWrap overflowX overflowY overscrollBehavior overscrollBehaviorBlock
overscrollBehaviorInline overscrollBehaviorX overscrollBehaviorY padding paddingBlock paddingBlockEnd
paddingBlockStart paddingBottom paddingInline paddingInlineEnd paddingInlineStart paddingLeft paddingRight
paddingTop page pageBreakAfter pageBreakBefore pageBreakInside paintOrder perspective perspectiveOrigin
placeContent placeItems placeSelf pointerEvents position positionAnchor positionArea positionTry
positionTryFallbacks positionTryOrder positionVisibility printColorAdjust quotes r resize right rotate
rowGap rubyAlign rubyPosition rx ry scale scrollBehavior scrollMargin scrollMarginBlock
scrollMarginBlockEnd scrollMarginBlockStart scrollMarginBottom scrollMarginInline scrollMarginInlineEnd
scrollMarginInlineStart scrollMarginLeft scrollMarginRight scrollMarginTop scrollPadding
scrollPaddingBlock scrollPaddingBlockEnd scrollPaddingBlockStart scrollPaddingBottom scrollPaddingInline
scrollPaddingInlineEnd scrollPaddingInlineStart scrollPaddingLeft scrollPaddingRight scrollPaddingTop
scrollSnapAlign scrollSnapStop scrollSnapType scrollTimeline scrollTimelineAxis scrollTimelineName
scrollbarColor scrollbarGutter scrollbarWidth shapeImageThreshold shapeMargin shapeOutside
shapeRendering stopColor stopOpacity stroke strokeDasharray strokeDashoffset strokeLinecap
strokeLinejoin strokeMiterlimit strokeOpacity strokeWidth tabSize tableLayout textAlign textAlignLast
textAnchor textAutospace textBox textBoxEdge textBoxTrim textCombineUpright textDecoration
textDecorationColor textDecorationLine textDecorationSkipInk textDecorationStyle
textDecorationThickness textEmphasis textEmphasisColor textEmphasisPosition textEmphasisStyle
textIndent textJustify textOrientation textOverflow textRendering textShadow textTransform
textUnderlineOffset textUnderlinePosition textWrap textWrapMode textWrapStyle timelineScope top
touchAction transform transformBox transformOrigin transformStyle transition transitionBehavior
transitionDelay transitionDuration transitionProperty transitionTimingFunction translate unicodeBidi
userSelect vectorEffect verticalAlign viewTimeline viewTimelineAxis viewTimelineInset viewTimelineName
viewTransitionClass viewTransitionName visibility webkitAlignContent webkitAlignItems webkitAlignSelf
webkitAnimation webkitAnimationDelay webkitAnimationDirection webkitAnimationDuration
webkitAnimationFillMode webkitAnimationIterationCount webkitAnimationName webkitAnimationPlayState
webkitAnimationTimingFunction webkitAppearance webkitBackfaceVisibility webkitBackgroundClip
webkitBackgroundOrigin webkitBackgroundSize webkitBorderBottomLeftRadius
webkitBorderBottomRightRadius webkitBorderRadius webkitBorderTopLeftRadius
webkitBorderTopRightRadius webkitBoxAlign webkitBoxFlex webkitBoxOrdinalGroup webkitBoxOrient
webkitBoxPack webkitBoxShadow webkitBoxSizing webkitFilter webkitFlex webkitFlexBasis
webkitFlexDirection webkitFlexFlow webkitFlexGrow webkitFlexShrink webkitFlexWrap
webkitJustifyContent webkitLineClamp webkitMask webkitMaskBoxImage webkitMaskBoxImageOutset
webkitMaskBoxImageRepeat webkitMaskBoxImageSlice webkitMaskBoxImageSource webkitMaskBoxImageWidth
webkitMaskClip webkitMaskComposite webkitMaskImage webkitMaskOrigin webkitMaskPosition webkitMaskRepeat
webkitMaskSize webkitOrder webkitPerspective webkitPerspectiveOrigin webkitTextFillColor
webkitTextSizeAdjust webkitTextStroke webkitTextStrokeColor webkitTextStrokeWidth webkitTransform
webkitTransformOrigin webkitTransformStyle webkitTransition webkitTransitionDelay
webkitTransitionDuration webkitTransitionProperty webkitTransitionTimingFunction webkitUserSelect
whiteSpace whiteSpaceCollapse widows width willChange wordBreak wordSpacing wordWrap writingMode x y
zIndex zoom
`

/** CSSStyleDeclaration properties supported by typed Foldkit style objects.
 *
 * @internal
 */
export const CSS_STYLE_PROPERTIES: ReadonlySet<string> = new Set(
  CSS_STYLE_PROPERTY_SOURCE.trim().split(/\s+/),
)
