export { Coins, initialModel, isEditing, Model } from './model'
export { Message, OutMessage } from './message'
export { AddCoin, DeleteCoin, FetchCoins, informRouteChanged, init, NavigateCoins, readCoins, update } from './update'
export { SaveCoin, SearchCoins } from './update'
export { view } from './view'
