packages:
  - 'packages/*'
  - 'packages/typing-game/*'
  - 'examples/*'
  - 'comparisons/*'
  - 'internal/*'

allowBuilds:
  '@parcel/watcher': true
  msgpackr-extract: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@effect/platform-browser@4.0.0-rc.117'
  - '@effect/platform-node-shared@4.0.0-rc.117'
  - '@effect/platform-node@4.0.0-rc.117'
  - '@effect/vitest@4.0.0-rc.117'
  - effect@4.0.0-rc.117
  - '@livestore/adapter-web@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/common-cf@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/common@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/livestore@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/peer-deps@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/sqlite-wasm@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/utils@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/wa-sqlite@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'
  - '@livestore/webmesh@0.0.0-snapshot-287936d11d3e6c7afbaacaf1ece14bf162120219'

overrides:
  '@mapbox/jsonlint-lines-primitives': 2.0.2
  '@types/node': 26.4.0
  effect: 4.0.0-rc.117
  '@effect/platform-browser': 4.0.0-rc.117
  '@effect/platform-node': 4.0.0-rc.117
  '@effect/platform-node-shared': 4.0.0-rc.117
  '@effect/vitest': 4.0.0-rc.117
  'monaco-editor>dompurify': 3.4.14
